<?php
use yogi\framework\helpers\Html;
use src\models\viewmodels\LayoutViewModel;
/**
 * @var model LayoutViewModel
 */
?>
<!DOCTYPE HTML>
<html ng-app="iflvgApp">
<head>
	<title><?php print $model->title;?></title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="~/src/assets/prettify.css" rel="stylesheet">
	<link href="~/src/assets/main.css" rel="stylesheet">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body class="base-layout">

		<?php 
			print Html::renderAction("topNav", "Nav"); 
		?>
		<?php
			print $this->renderSection('Header');
		?>
		<?php
			print $content;
		?>


  

  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<script src="~/src/scripts/prettify.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
	<script src="~/src/scripts/app.js"></script>
</body>
</html>